### PR TITLE
Black pre commit

### LINKED ISSUE #17: Add Black pre-commit
https://pre-commit.com
https://github.com/ambv/black

This would in theory run black on anything that is being checked in, which has several advantages:
"Black makes code review faster by producing the smallest diffs possible."

It also completely ends the Tab/Space discussion or ' vs ".

Note that for safety black checks that the .pyc file is no different after running black.

### PR DESCRIPTION
**Pull request by mtik00**
Adding the `pre-commit` project and hooks for `black` and `flake8`.

Close #17

### CODE REVIEW

**Review by ryanfreckleton — DISMISSED** [review]
LGTM

**Comment by mtik00** [comment]
Ran into an issue with `Pipfile.lock`, sorry.

**Review by ryanfreckleton — COMMENTED** [review]
LGTM

**Review by ryanfreckleton — DISMISSED** [review]

**Comment by mtik00** [comment]
I don't know why I keep getting conflicts, so I'm just going to merge this in.

**Pull request merged**
